language: generic
sudo: required
services:
- docker
before_install:
- docker build -t mideg3/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true mideg3/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-760665699577
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
env:
  global:
  - secure: O+cgLyWxCfAuNK9DXLmgYuuf+e50HI64evfpH4GIKZVrNI7JpoJmMCK/z6FnJPw5lxWWR3EDS0MU6NobSSg6GxCD3q6UAzVvucKHuqzgoi4Z8mds9bnXjluFfZUn1GZi8GTGUGtX8rEjQZHC198keRdCZ0GBW1nFH8JuGx0lk0Eno3ZFUTEmJhw0mEcEpy5EX/LlG/f150PWfYXrZzNzIErNLk3cpN3rKtOswPxbDg6DtEFylgzttgtjNkI8KXmN2hVsuxWHk/mh0DvVrjuw9SKU8lj2mdbN2FKe5H6C+oY9HkNrXVENXT56Rxd5BKohVEulasKYNvH1ciJbsLTMb6WNH/1dqcwwTPPmE98sFtBIeCPsdZfdnHzTvJbLAdOlMsx0ZSq/qCzAv8laA8MfA2E//Tmu1QNr1XOGjGp7VByDUJ//T135YYZJ6Zf0rgJCYJhUsjkn8b23BJOPQpXSl7HM19C13VZUGeDJ0a61r1mjFk0OKwji04oqBrV22QMw50r8M/TLu0DPlPqrRI04/uSZDnT+5cI8t8Hr7kxEr7wSepsk3DM2hAsRpoytZXZS/3S5o9AcERbaT0BUc8A5PEGVWTeQ+FtjtDHNv7peAHHxA9UbMj2h5WyOHH5AQQZWYus11pF0DMyOIKwgSI7C3aCkcu/eqLn3xW9pXQ9/6Ig=
  - secure: ZY4WipGnAMR50ztN4M8IY3jlj/QEoNcTPvL21Ea4rijPwpznNHqkVlaKFDd3uk5hCCO8wSQ0yFcKgJO7lGD9SEct32AKolFAt9UBtQJrisNI1HHhvAoE+ce7GOwLUt6RzRhh57N7Mh7Mq1sO16w0DWdu49V96Mc/ZOwJ/5kamNhWjiJ0oncWpTafxWirnGmAsbSRDOYLdPh6YFdQH29ieTe0NPO5ccs0G7gzMd6EHsKdp38XYCYXC3XaBqAGv6EHxWnian9BZRL8pFRj5gxjVtpO1ypb85fso7upM+vlvFQ7oeiYWWCLrJYMGj9oh+UfDSkfpqt4PEaCpRgmjHtoZUtH8G/XosSh8c39Gw4ajyNos7foyvgCoAu7CGDNgvOXoKmZ902S1m1mLj2J4MCH8bHwI29FqOCKHxXQn31p/0c0NTGCIhRKsoej5bliiA8lPZnoaAkxkl/st6vMeB45uB7DwMt8JhncK1Lz9L0rboYGizs9Cou4ICdqwfU9VRGPmWVgfcfjOVZ8Ish7sUNbB/v53a+9H/L8siQl8V1Sb6FB65Zyt3IiJnK4PX6FfcOxhPnPyN4QIHGyfhhcFg3FUNcEZvak+EFaB2e2X6Ra2yZqFWTXpRrKiF8RyMYr6QMmtqWyaRntP9VESoLN/ImSxos7AebNwyn6sYEYBOOHVQw=
