language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mideg3/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mideg3/docker-react npm run test -- --coverage